name: Go

on:
  push:
    branches: [master, vbe/master]
  pull_request:
    branches: [master, vbe/master]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.16.x", "1.17.x", "1.x"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Load cached dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Test
      run: go test -v -race ./...
